=== lxvhit/BTLXML/Category.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="DSSanpham">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sanpham" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"></xs:element>
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="50" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Category_id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1" />
                                        <xs:maxInclusive value="9" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="desscription">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z_0-9\s\p{L}]{0,128}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="amount">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="9999" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="100" /> 
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Created_at" type="xs:dateTime"></xs:element>
                            <xs:element name="image">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value=".jpeg"></xs:enumeration>
                                                        <xs:enumeration value=".png"></xs:enumeration>
                                                        <xs:enumeration value=".jpg"></xs:enumeration>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="unique_id">
            <xs:selector xpath=".//*" />
            <xs:field xpath="id" />
        </xs:unique>
    </xs:element>

</xs:schema>

=== lxvhit/BTLXML/Category.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet href="Category.css" type="text/css"?> -->
<?xml-stylesheet type="text/xsl" href="Category.xsl"?>
<DSSanpham xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Category.xsd">
    <Sanpham>
        <id>1</id>
        <name>Iphone 6</name>
        <Category_id>1</Category_id>
        <desscription>Điện thoại iphone</desscription>
        <amount>100</amount>
        <price>1000000</price>
        <Created_at>2020-01-01</Created_at>
        <image type=".jpeg">hoang</image>
    </Sanpham>
    <Sanpham>
        <id>2</id>
        <name>Xaomi</name>
        <Category_id>2</Category_id>
        <desscription>Điện thoại xaomi</desscription>
        <amount>200</amount>
        <price>200000</price>
        <Created_at>2020-02-02</Created_at>
        <image type=".jpeg">Anh.png</image>
    </Sanpham>
    <Sanpham>
        <id>3</id>
        <name>Samsung galaxy</name>
        <Category_id>3</Category_id>
        <desscription>Điện thoại samsung</desscription>
        <amount>1000</amount>
        <price>1000000</price>
        <Created_at>2021-02-02</Created_at>
        <image>1.jpg</image>
    </Sanpham>
    <Sanpham>
        <id>4</id>
        <name>VinPro</name>
        <Category_id>4</Category_id>
        <desscription>Điện thoại vin</desscription>
        <amount>1</amount>
        <price>100000000</price>
        <Created_at>2020-02-02</Created_at>
        <image>Pro.jpg</image>
    </Sanpham>
</DSSanpham>
